01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/live/urls.py
from django.urls import path

from . import views

app_name = 'live'

urlpatterns = [
    path("info/", views.info, name='info'),
    path("record/", views.info),
    path("record/<int:id>/<int:term>/", views.record, name='record'),
    path('video/', views.process_media, name='process_media'),
    path('time/', views.update_lecture_time, name='update_lecture_time'),
]

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/monitoring/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from monitoring import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.main),
    path("live/", include("live.urls")),
    path("user/", include("user.urls")),
    path("report/", include("report.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/report/urls.py
from django.urls import path

from . import views

app_name = 'report'

urlpatterns = [
    path("list/", views.list_lectures, name="list_lectures"),
    path("result/<int:id>/", views.result, name="detail"),
    path("list/delete/", views.delete_lecture, name="delete_lecture"),
]

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/report/models.py
from django.db import models

from live.models import Lecture


# Create your models here.
class Reaction(models.Model):
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE)
    time = models.IntegerField()
    concentration = models.IntegerField()
    negative = models.IntegerField()
    neutral = models.IntegerField()
    positive = models.IntegerField()

    class Meta:
        db_table = 'reaction'


class Feedback(models.Model):
    reaction = models.OneToOneField(Reaction, on_delete=models.CASCADE, primary_key=True)
    content = models.TextField()

    class Meta:
        db_table = 'feedback'

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/report/views.py
# Create your views here.
import json
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.csrf import csrf_exempt

from live.models import Lecture
from report.models import Reaction


@login_required
def result(request, id):
    if request.method == 'GET':
        lecture = get_object_or_404(Lecture, pk=id)
        reactions = Reaction.objects.filter(lecture=lecture).order_by('time')
        reaction_count = reactions.count()

        averages = {
            'concentration': sum(
                reaction.concentration for reaction in reactions) / reaction_count if reaction_count else 0,
            'negative': sum(reaction.positive for reaction in reactions) / reaction_count if reaction_count else 0,
            'neutral': sum(reaction.neutral for reaction in reactions) / reaction_count if reaction_count else 0,
            'positive': sum(reaction.negative for reaction in reactions) / reaction_count if reaction_count else 0,
        }

        reactions_with_feedbacks = [
            {
                'time': reaction.time,
                'concentration': reaction.concentration,
                'negative': reaction.negative,
                'neutral': reaction.neutral,
                'positive': reaction.positive,
                'feedback': escape_control_characters(reaction.feedback.content) if reaction.feedback else '피드백이 없습니다.',
            }
            for reaction in reactions
        ]

        reactions_json = json.dumps(reactions_with_feedbacks, ensure_ascii=False)
        time_diff = calculate_elapsed_time(lecture.start_time, lecture.end_time)

        lecture.category += display_category(lecture.category)

        context = {
            'lecture': lecture,
            'reactions_json': reactions_json,
            'averages': averages,
            'time_diff': time_diff,
        }

        return render(request, 'report/report_page.html', context)

    if request.method == 'POST':
        pass


def escape_control_characters(s):
    if not isinstance(s, str):
        return ''

    return s.translate(str.maketrans({
        '\b': '\\b',
        '\f': '\\f',
        '\n': '\\n',
        '\r': '\\r',
        '\t': '\\t',
    }))


def calculate_elapsed_time(start_time, end_time):
    if start_time and end_time:
        start_time = datetime.combine(datetime.today(), start_time)
        end_time = datetime.combine(datetime.today(), end_time)
        time_diff = end_time - start_time

        return round(time_diff.total_seconds() / 60)

    return 0


def display_category(category):
    if category == '교육용':
        return ': 강의 및 워크숍, 학습 효과 분석'
    elif category == '기업용':
        return ': 회의 및 프레젠테이션, 직원 교육'
    elif category == '공연예술':
        return ': 연극, 뮤지컬, 콘서트, 대중 강연'
    elif category == '정치사회':
        return ': 선거 유세, 공공 포럼, 토론'
    else:
        return '기타'


@login_required
def list_lectures(request):
    if request.method == 'GET':
        search_query = request.GET.get('search', '')
        page_number = request.GET.get('page', 1)

        lectures_query = (Lecture.objects
                          .filter(Q(user=request.user), Q(topic__icontains=search_query))
                          .order_by('-datetime').distinct())

        paginator = Paginator(lectures_query, 10)

        try:
            lectures = paginator.page(page_number)
        except PageNotAnInteger:
            lectures = paginator.page(1)
        except EmptyPage:
            lectures = paginator.page(paginator.num_pages)

        context = {'lectures': lectures}
        return render(request, 'report/storage_list.html', context)


@csrf_exempt
def delete_lecture(request):
    if request.method == "POST":
        lecture_id = request.POST.get("lecture_id")
        if not lecture_id:
            return JsonResponse({'error': 'No lecture ID provided'}, status=400)

        lecture = get_object_or_404(Lecture, id=lecture_id, user=request.user)
        lecture.delete()

        return JsonResponse({'message': 'Lecture deleted successfully'})

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/templates/report/report_page.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <!-- 핵심 테마 CSS (부트스트랩 포함) -->
    <link href="{% static 'css/report-page.css' %}" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        @media (min-width: 1200px) {
            .chart-container {
                flex-direction: column;
            }

        }

        @media (max-width: 970px) {
            .container-fluid {
                padding-left: 0 !important;
            }
        }

        .box {
            margin-left: 30px;
            margin-top: 60px;
            margin-bottom: 50px;
            border: 1px solid black;
        }
    </style>

    <main style="padding-top: 80px !important;">
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="height: 150px; padding:0">
            <div class="container-fluid" style="padding-left: 100px;">
                <h3 class="navbar-brand"
                    style="font-size: 35px !important; ">{{ lecture.topic }}</h3>
            </div>
        </nav>
        <div class="mb-auto p-5 container contents-center">
            <div style="width: 100%">
                <div style="display: flex; flex-direction: row;">
                    {{ averages|json_script:"averages-data" }}
                    <div class="lecture-content" style="width: 50%;">
                        <h4>강의자</h4>
                        <p>{{ lecture.user.name }}</p>
                        <h4>카테고리</h4>
                        <p>{{ lecture.category }}</p>
                        <h4>강의 일자</h4>
                        <p>{{ lecture.datetime|date:"Y.m.d" }}</p>
                        <h4>강의 시간</h4>
                        <p>{{ time_diff }}분</p>
                    </div>
                    <div class="lecture-content" style="width: 50%; padding: 0 50px;">
                        <canvas id="emotionDoughnutChart" style="height: 391px"></canvas>
                    </div>
                </div>
            </div>
            <hr style="width: 100%">
            <div class="chart-container" style="display: flex; flex-direction: row; margin-top:80px;">
                <div style="padding-right: 20px;">
                    <div>
                        <canvas id="chart-left" style="width: 688px; height: 400px;"></canvas>
                    </div>
                    <hr style="border: 1px solid lightgrey">
                    <div style="width: auto">
                        <canvas id="chart-right" style="width: 688px; height: 400px;"></canvas>
                    </div>
                </div>
                <div class="overall-feedback" style="border-left: 1px solid lightgrey;">
                    <h4 style="padding: 12px; border-left: 5px solid black">피드백</h4>
                    <div id="feedback-display" style="white-space: pre-wrap; padding: 20px; font-size: 20px;">
                        그래프 위에 마우스를 올려 피드백을 확인하세요.
                    </div>
                </div>
            </div>
        </div>
    </main>
    <script type="text/javascript">
        const reactions = JSON.parse('{{ reactions_json|safe }}');
        const averages = JSON.parse(document.getElementById('averages-data').textContent);
    </script>

    <script src="{% static 'js/report-chart.js' %}"></script>
    <script src="{% static 'js/navbar_current_page_underline_effect.js' %}"></script>
{% endblock %}

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/templates/report/storage_list.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
    <!-- 핵심 테마 CSS (부트스트랩 포함) -->
    <link href="{% static 'css/storage-list.css' %}" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <style>
        @media (min-width: 768px) {
            /* md 사이즈 이상일 때 */
            .custom-border {
                border-right: dotted;
                border-bottom: none;
            }
        }

        @media (max-width: 767.98px) {
            /* md 사이즈 미만일 때 */
            .custom-border {
                border-right: none;
                border-bottom: dotted;
            }
        }
    </style>
    </head>
    <body>

    <section class="notice" style="padding-top: 120px !important; min-height:100%">
        <div class="page-title">
            <div class="container">
                <h3 style="font-weight:700;">강의 기록</h3>
            </div>
        </div>

        <!-- board seach area -->
        <div id="board-search">
            <div class="container">
                <div class="search-window">
                    <form method="get">
                        <div class="search-wrap">
                            <label for="search" class="blind">강의 내용 검색</label>
                            <input id="search" type="text" name="search" placeholder="검색어를 입력해주세요."
                                   value="{{ request.GET.search }}">
                            <button type="submit" class="btn btn-dark"
                                    style="--bs-btn-border-color: #5a9e93; --bs-btn-bg: #5a9e93">검색
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- board list area -->
        <div id="board-list">
            <div class="container">
                <table class="board-table">
                    <thead>
                    <tr>
                        <th scope="col" class="th-num">번호</th>
                        <th scope="col" class="th-title">제목</th>
                        <th scope="col" class="th-date">등록일</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for lecture in lectures %}
                        <tr>
                            <td>{{ forloop.counter0|add:lectures.start_index }}</td>
                            <th>
                                <a href="{% url 'report:detail' lecture.id %}"
                                   style="text-decoration: none">{{ lecture.topic }}</a>
                                <p>테스트</p>
                            </th>
                            <td>{{ lecture.datetime|date:"Y.m.d" }}</td>
                            <td>
                                <button class='delete' lecture_id={{ lecture.id }}>삭제<i class="fa fa-trash"></i>
                                </button>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="3" style="text-align: center;">분석 결과가 없습니다</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        <div class="pagination">
    <span class="step-links destroy-box">
        <a href="?page=1">«</a>
        {% if lectures.has_previous %}
            <a href="?page={{ lectures.previous_page_number }}">‹</a>
        {% else %}
            <a href="?page={{ lectures.number }}">‹</a>
        {% endif %}

        {% for i in lectures.paginator.page_range %}
            {% if lectures.number == i %}
                <span class="current"> {{ i }} </span>
            {% else %}
                <a href="?page={{ i }}"> {{ i }} </a>
            {% endif %}
        {% endfor %}

        {% if lectures.has_next %}
            <a href="?page={{ lectures.next_page_number }}">›</a>
        {% else %}
            <a href="?page={{ lectures.number }}">›</a>
        {% endif %}
        <a href="?page={{ lectures.paginator.num_pages }}">»</a>
    </span>
        </div>
    </section>

    <!-- Bootstrap core JS-->
    <script>
        $('.delete').click(function (e) {
            var ans = confirm('정말로 삭제하시겠습니까?');
            let lecture_id = e.target.attributes.getNamedItem('lecture_id').value;
            if (ans) {
                $.ajax({
                    url: '/report/list/delete/',
                    data: {
                        lecture_id: lecture_id
                    },
                    method: 'POST',
                    success: function (result) {
                        console.log('성공')
                        location.replace('/report/list');
                        location.reload(true);
                    },
                    error: function (result, status, error) {
                        console.log('에러')
                        console.log(result);
                        console.log(status);
                        console.log(error);
                    }
                });
            }
        })
    </script>
{% endblock %}