01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/live/urls.py
from django.urls import path

from . import views

app_name = 'live'

urlpatterns = [
    path("info/", views.info, name='info'),
    path("record/", views.info),
    path("record/<int:id>/<int:term>/", views.record, name='record'),
    path('video/', views.process_media, name='process_media'),
    path('time/', views.update_lecture_time, name='update_lecture_time'),
]

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/monitoring/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from monitoring import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.main),
    path("live/", include("live.urls")),
    path("user/", include("user.urls")),
    path("report/", include("report.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/user/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path('check_userid/', views.check_userid_existence, name='check_userid'),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/user/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.base_user import BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):
    def get_by_natural_key(self, userid):
        return self.get(**{self.model.USERNAME_FIELD: userid})

    def create_user(self, userid, email, name, password=None, **extra_fields):
        """
        Create and save a User with the given userid and password.
        """
        if not userid:
            raise ValueError(_('The User ID must be set'))
        if not email:
            raise ValueError(_('The User Email must be set'))

        email = self.normalize_email(email)
        user = self.model(userid=userid, email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, userid, password=None, **extra_fields):
        """
        Create and save a SuperUser with the given userid and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))

        return self.create_user(userid, password, **extra_fields)


class User(AbstractBaseUser):
    userid = models.CharField(max_length=30, unique=True)
    name = models.CharField(max_length=24)
    email = models.EmailField(unique=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'userid'  # 고식별이 될 필드

    class Meta:
        db_table = "user"

    @property
    def is_anonymous(self):
        """
        Always return False. This is a way of comparing User objects to
        anonymous users.
        """
        return False

    @property
    def is_authenticated(self):
        """
        Always return True. This is a way to tell if the user has been
        authenticated in templates.
        """
        return True

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/user/views.py
# Create your views here.
import re

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from user.models import User


@csrf_exempt
def check_userid_existence(request):
    if request.method == "GET":
        userid = request.GET.get('userid')
        is_taken = User.objects.filter(userid=userid).exists()

        return JsonResponse({'is_taken': is_taken})


@csrf_exempt
def signup_view(request):
    if request.method == "GET":
        return render(request, "user/sign_up.html")

    if request.method == "POST":
        userid = request.POST.get("userid")
        password = request.POST.get("password")
        password_confirm = request.POST.get("password_confirm")
        name = request.POST.get("name")
        email = request.POST.get("email")

        error_message = validate_signup_data(userid, password, password_confirm, name, email)
        if error_message:
            return render(request, "user/sign_up.html", {"error": error_message})

        user = User(
            userid=userid,
            password=make_password(password),
            name=name,
            email=email
        )
        user.save()

        return redirect("user:login")


def validate_signup_data(userid, password, password_confirm, name, email):
    return (
            validate_userid(userid) or
            validate_password(password, userid, name, email) or
            validate_password_confirmation(password, password_confirm)
    )


def validate_userid(userid):
    if not userid or not re.match("^[a-zA-Z0-9]{6,15}$", userid):
        return "아이디는 6~15자리의 영문자와 숫자로 이루어져야 합니다."

    if User.objects.filter(userid=userid).exists():
        return "이미 존재하는 사용자 ID입니다."

    return None


def validate_password(password, userid, name, email):
    if not password or len(password) < 8:
        return "비밀번호는 최소 8자 이상이어야 합니다."

    patterns = ["[0-9]", "[a-z]", "[A-Z]", "[^0-9a-zA-Z]"]
    if sum(bool(re.search(pattern, password)) for pattern in patterns) < 3:
        return "비밀번호는 숫자, 소문자, 대문자, 특수 문자 중 최소 3가지를 포함해야 합니다."

    return None


def validate_password_confirmation(password, password_confirm):
    if password != password_confirm:
        return "비밀번호가 일치하지 않습니다."

    return None


@csrf_exempt
def login_view(request):
    if request.method == "GET":
        next_url = request.GET.get("next") or "/"
        return render(request, "user/login_page.html", {"next": next_url})

    if request.method == "POST":
        next_url = request.POST.get("next") or "/"
        userid = request.POST.get("userid").strip()
        password = request.POST.get("password").strip()
        remember_me = request.POST.get("remember_me")

        if not userid or not password:
            return render(request, "user/login_page.html", {"error": "아이디와 비밀번호를 입력해주세요.", "next": next_url})

        user = authenticate(request, username=userid, password=password)
        if user is not None:
            login(request, user)
            request.session.set_expiry(3600 * 24 * 30 if remember_me else 0)

            if next_url.startswith("/live/record/"):
                return redirect("live:info")
            else:
                return redirect(next_url)
        else:
            return render(request, "user/login_page.html", {"error": "아이디 또는 비밀번호가 올바르지 않습니다."})


@csrf_exempt
def logout_view(request):
    logout(request)
    return redirect("/")

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/templates/user/login_page.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, 그리고 Bootstrap 기여자들">
    <meta name="generator" content="Hugo 0.115.4">
    <title>청중의소리를부탁해</title>
    <link rel="canonical" href="https://getbootstrap.kr/docs/5.3/examples/sign-in/">
    <link href="{% static 'css/login-page.css' %}" rel="stylesheet">
    <link rel="icon" href="../../static/img/favicon.ico">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <!-- Favicons -->
    <meta name="theme-color" content="#712cf9">
</head>
<body class="d-flex align-items-center py-4 bg-body-tertiary" style="background-color: white !important;">

<main class="form-signin w-100 m-auto" style="border-radius: 10px; border:1px solid #E6E6E6; max-width: 450px;">
    <form method="post" id="login_form" name="login_form">
        <a class="navbar-brand">
            <img style="height:200px; margin: auto; display: block"
                 src="{% static 'img/introduction-page-img/logo-06.png' %}"><br><br>
        </a>

        <div class="form-floating">
            <input type="text" class="form-control"
                   style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; box-shadow: none; border:1px solid lightgrey"
                   placeholder=""
                   id="id" name="userid" required>
            <label for="floatingInput">ID</label>
        </div>
        <div class="form-floating">
            <input style="box-shadow: none; border:1px solid lightgrey" type="password" class="form-control" id="pw"
                   name="password" placeholder="" required>
            <label for="floatingPassword">Password</label>
        </div>

        <div class="form-check text-start my-3">
            <input class="form-check-input" type="checkbox" id="flexCheckDefault" name="remember_me">
            <label class="form-check-label" for="flexCheckDefault" style="color:black">
                Remember me
            </label>
        </div>

        <input type="hidden" name="next" value="{{ next }}">
        <button style="font-weight: bold; margin-top: 30px;" class="btn w-100 py-2" type="submit" id="login_btn">로그인
        </button>
        <button id="cancel_btn" style="margin-top:10px;font-weight: bold;" class="btn w-100 py-2"
                onclick="location.href='/'">취소
        </button>
    </form>
    <div class="text-center pt-2">계정이 없으신가요?<a style="color:black; " class="text-center sign-up-button"
                                               href="{% url 'user:signup' %}">
        회원가입</a></div>
    {#    <p>{{ error }}</p>#}
</main>


<script src="{% static 'js/login-page-alert.js' %}"></script>
</body>
</html>