01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/live/urls.py
from django.urls import path

from . import views

app_name = 'live'

urlpatterns = [
    path("info/", views.info, name='info'),
    path("record/", views.info),
    path("record/<int:id>/<int:term>/", views.record, name='record'),
    path('video/', views.process_media, name='process_media'),
    path('time/', views.update_lecture_time, name='update_lecture_time'),
]

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/monitoring/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from monitoring import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.main),
    path("live/", include("live.urls")),
    path("user/", include("user.urls")),
    path("report/", include("report.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/user/urls.py
from django.urls import path

from . import views

app_name = "user"

urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path('check_userid/', views.check_userid_existence, name='check_userid'),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/templates/cover-page.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>청중의 소리를 부탁해</title>
    <link rel="stylesheet" href="../static/css/cover-page.css">
</head>
<body>
<div class="background-image">
    <div btn-container>
        <button>시작하기</button>
    </div>
</div>
</body>
</html>

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>청중의소리를부탁해</title>
    <!-- 파비콘 -->
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}"/>
    <!-- Font Awesome 아이콘 (무료 버전) -->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- 구글 폰트 -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
          type="text/css"/>
    <!-- 핵심 테마 CSS (부트스트랩 포함) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link href="{% static 'css/intoduction-page.css' %}" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js"
            integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <link href="{% static 'css/intoduction-page.css' %}" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet">
    {#    <link href="{% static 'css/storage-list.css' %}"/>#}
</head>
<style>
    @media (min-width: 992px) {
        .navbar-collapse {
            background-color: white;
        !important;
        }
    }
</style>
<body style="height: 100%">
<header class="mb-auto p-5" style="padding: 0 !important;">
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav"
         style="background-color:white !important; border-bottom: 1px solid lightgrey; ">
        <div class="container" style="position: fixed; top: 0; right: 0; left: 0;">
            <a class="navbar-brand" href="/" id='nav-btn'>
                <img src="{% static 'img/introduction-page-img/m_logo.png' %}">
            </a>
            <button class="navbar-toggler text-uppercase font-weight-bold text-white rounded" type="button"
                    data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive"
                    aria-expanded="false" aria-label="Toggle navigation" style="color: black !important;">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto"
                    style="text-align: center; background-color: white; margin-top: 0 !important;">
                    <li class="nav-item mx-0 mx-lg-1">
                        <a id='nav-btn' class="nav-link py-3 px-0 px-lg-3 rounded" href="/">소개</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a id='nav-btn' class="nav-link py-3 px-0 px-lg-3 rounded" href="/live/info/">청중</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a id='nav-btn' class="nav-link py-3 px-0 px-lg-3 rounded" href="/report/list/">분석 저장소</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item mx-0 mx-lg-1">
                            <a id='nav-btn' class="nav-link py-3 px-0 px-lg-3 rounded"
                               href="{% url 'user:logout' %}">LOGOUT</a>
                        </li>
                    {% else %}
                        <li class="nav-item mx-0 mx-lg-1">
                            <a id='nav-btn' class="nav-link py-3 px-0 px-lg-3 rounded"
                               href="{% url 'user:login' %}">LOGIN</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
{% block content %}
{% endblock %}
<!-- Footer Section -->


<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const currentLocation = window.location.href;

        const navLinks = document.querySelectorAll('nav ul li a');

        navLinks.forEach(function (link) {
            if (link.href !== window.location.origin + '/') {
                if (currentLocation.startsWith(link.href)) {
                    link.classList.add('active');
                }
            } else {
                if (currentLocation === link.href) {
                    link.classList.add('active');
                }
            }
        });
    });
</script>
<script src="{% static 'js/scripts.js' %}"></script>
</body>
<footer class="mb-auto">
    <div class="copyright py-1 text-center text-white footer-bot">
        <div class="container" style="color: black; background-color: white;"><small>Copyright &copy; 청중을 구해조</small>
        </div>
    </div>
</footer>
</html>

01. KT 에이블스쿨 4기 프로젝트 (2023) /02. 최종 프로젝트 (청중의 소리를 부탁해)/code/Web/templates/main.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <main class="mb-auto p-5" style="min-height:100%; padding-top: 80px !important; background-color: #e4f1fe;">
        <section class="page-section portfolio" id="portfolio">
            <div class="container">
                <!-- Portfolio Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">청중 분석 서비스 소개</h2>
                <br><br><br>
                <!-- Portfolio Grid Items-->
                <div class="row justify-content-center">
                    <!-- Portfolio Item 1-->
                    <div class="col-md-6 col-lg-4 mb-5">
                        <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal1">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i
                                        class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <img class="img-fluid" src="../static/img/introduction-page-img/intro_t.png" alt="..."/>
                        </div>
                    </div>
                    <!-- Portfolio Item 2-->
                    <div class="col-md-6 col-lg-4 mb-5">
                        <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal2">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i
                                        class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <img class="img-fluid" src="../static/img/introduction-page-img/intro2_t.png" alt="..."/>
                        </div>
                    </div>
                    <!-- Portfolio Item 3-->
                    <div class="col-md-6 col-lg-4 mb-5">
                        <div class="portfolio-item mx-auto" data-bs-toggle="modal" data-bs-target="#portfolioModal3">
                            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                                <div class="portfolio-item-caption-content text-center text-white"><i
                                        class="fas fa-plus fa-3x"></i></div>
                            </div>
                            <img class="img-fluid" src="../static/img/introduction-page-img/intro3_t.png" alt="..."/>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Portfolio Modal 1-->
        <div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" aria-labelledby="portfolioModal1"
             aria-hidden="true">
            <div class="modal-dialog modal-xl">
                <div class="modal-content">
                    <div class="modal-header border-0">
                        <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body text-center pb-5">
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-lg-8">
                                    <!-- Portfolio Modal - Title-->
                                    <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">청중 분석
                                        서비스란?</h2>
                                    <br><br>
                                    <!-- Portfolio Modal - Image-->
                                    <img class="img-fluid rounded mb-5"
                                         src="../static/img/introduction-page-img/intro_m.png" alt="..."/>
                                    <!-- Portfolio Modal - Text-->
                                    <!-- <p class="mb-4">청중 반응 분석 서비스는 강연 및 PT에 대한 설문 과정을 생략하여</p>
                                    <p class="mb-4">사용자와 청중 사이에서 기존의 피드백 시스템 보다 더 편리한</p>
                                    <p class="mb-4">피드백 시스템을 제공하기 위해 제작되었습니다.</p> -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Portfolio Modal 2-->
        <div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" aria-labelledby="portfolioModal2"
             aria-hidden="true">
            <div class="modal-dialog modal-xl">
                <div class="modal-content">
                    <div class="modal-header border-0">
                        <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body text-center pb-5">
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-lg-8">
                                    <!-- Portfolio Modal - Title-->
                                    <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">서비스 기술 소개</h2>
                                    <br><br>
                                    <!-- Portfolio Modal - Image-->
                                    <img class="img-fluid rounded mb-1"
                                         src="../static/img/introduction-page-img/intro2_m.png" alt="..."/>
                                    <!-- Portfolio Modal - Text-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Portfolio Modal 3-->
        <div class="portfolio-modal modal fade" id="portfolioModal3" tabindex="-1" aria-labelledby="portfolioModal3"
             aria-hidden="true">
            <div class="modal-dialog modal-xl">
                <div class="modal-content">
                    <div class="modal-header border-0">
                        <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body text-center pb-5">
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-lg-8">
                                    <!-- Portfolio Modal - Title-->
                                    <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">서비스 활용 방법</h2>
                                    <br><br>
                                    <!-- Portfolio Modal - Image-->
                                    <!-- <img class="img-fluid rounded mb-5" src="assets/img/portfolio/circus.png" alt="..." /> -->
                                    <div class="embed-responsive embed-responsive-16by9">
                                        <iframe class="embed-responsive-item" width="800" height="600"
                                                src="https://www.youtube.com/embed/o9isKgEC1N8"
                                                allowfullscreen></iframe>
                                    </div>
                                    <!-- Portfolio Modal - Text-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}